CREATE TABLE "User" (
	"id" INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL,
	"password" VARCHAR(60) NOT NULL,
	"gender" VARCHAR(1) NOT NULL,
	"roleId" INT NOT NULL
);