module.exports = {
  FIRST_NAME_REQUIRED: "First Name is required",
  LAST_NAME_REQUIRED: "Last Name is required",
  PASSWORD_REQUIRED: "Password is required",
  CURRENT_PASSWORD_WRONG: "Incorrect current password",
  ROLE_ID_REQUIRED: "Role Id is required",
  CURRENT_PASSWORD_REQUIRED: "Current password is required",
  NEW_PASSWORD_REQUIRED: "New password is required",
  USER_ID_REQUIRED: "User id is required",
  NAME_REQUIRED: "Name is required",
  IMAGE_REQUIRED: "Image is required",

  INVALID_EMAIL: "Please provide a valid email",
  INVALID_GENDER: "Allowed values for gender are m or f",
  INVALID_LOGIN_CREDENTIALS: "Email or password is incorrect",
  UNAUTHORIZED: "Unauthorized, make sure you have rights to access this route",
  SYSTEM_ERROR: "System error! please contact admin",
  BOTH_PASSWORD_SAME: "Both passwords cannot be same",
  PASSWORD_LENGTH: "Password should be atleast 8 characters long",
  USER_NOT_FOUND: "User not found",
};
